name: backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # чтобы не дублировать working-directory в каждом шаге
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt
          python -V
          pip -V
          pytest --version

      # Для CI используем локальную SQLite, чтобы не ходить в внешнюю БД
      - name: Create .env for tests
        run: |
          cat > .env <<EOF
          BACKEND_ENV=dev
          BACKEND_DATABASE_URL=sqlite:///./data.db
          BACKEND_ALLOWED_ORIGINS_RAW=http://localhost:5173,https://app.blackhole.bond
          EOF
          echo "---- .env ----"
          sed -e 's/BACKEND_DATABASE_URL=.*/BACKEND_DATABASE_URL=***MASKED***/' .env

      - name: Sanity import settings
        run: |
          python - <<'PY'
          from app.settings import settings
          print("env:", settings.env)
          print("db:", settings.database_url)
          print("origins:", settings.allowed_origins)
          PY

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q
