name: Manual Tests

on:
  workflow_dispatch:
    inputs:
      marker:
        description: "PyTest -k expression (optional, e.g. ping)"
        required: false
        default: ""
      verbose:
        description: "Verbose output (-vv)"
        type: boolean
        required: false
        default: false

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run pytest (manual)
        shell: bash
        run: |
          # соберём опции в массив (надёжнее, чем строки)
          PYARGS=()

          # маркер из inputs
          MARKER="${{ github.event.inputs.marker }}"

          # обрежем возможные кавычки по краям (и одинарные, и двойные)
          MARKER="${MARKER%\"}"; MARKER="${MARKER#\"}"
          MARKER="${MARKER%\'}"; MARKER="${MARKER#\'}"

          if [[ -n "$MARKER" ]]; then
            PYARGS+=(-k "$MARKER")
          fi

          if ${{ github.event.inputs.verbose }}; then
            OPTS=(-vv)
          else
            OPTS=(-q)
          fi

          echo "Running: pytest ${OPTS[*]} ${PYARGS[*]}"
          python -m pytest "${OPTS[@]}" "${PYARGS[@]}" --junitxml=pytest-report.xml


      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: backend/pytest-report.xml
